# Generated by Django 4.2.1 on 2023-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_detailinfo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
